name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - 'launchpad-website/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'launchpad-website/**'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - run: npm run lint

      - run: npx tsc -b --noEmit

      - run: npm run build

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - run: npm run build

      - run: npm run lint

      - run: npm run test
